# Generated by Django 2.1.2 on 2018-10-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=32)),
                ('quantity', models.IntegerField(default=0)),
                ('date', models.DateField(verbose_name='date arrives')),
                ('description', models.TextField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='PCs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=32)),
                ('quantity', models.IntegerField(default=0)),
                ('date', models.DateField(verbose_name='date arrives')),
                ('description', models.TextField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=32)),
                ('quantity', models.IntegerField(default=0)),
                ('date', models.DateField(verbose_name='date arrives')),
                ('description', models.TextField(max_length=120)),
            ],
        ),
    ]
