# Generated by Django 2.1.2 on 2018-10-10 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=32)),
                ('contact', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=32)),
                ('quantity', models.IntegerField(default=0)),
                ('date', models.DateField(verbose_name='date arrives')),
                ('description', models.TextField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Wed Oct 10 15:05:18 2018')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salesite.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=32)),
                ('quantity', models.IntegerField(default=0)),
                ('date', models.DateField(verbose_name='date arrives')),
                ('description', models.TextField(max_length=120)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salesite.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=32)),
                ('quantity', models.IntegerField(default=0)),
                ('date', models.DateField(verbose_name='date arrives')),
                ('description', models.TextField(max_length=120)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salesite.Order')),
            ],
        ),
        migrations.DeleteModel(
            name='Laptops',
        ),
        migrations.DeleteModel(
            name='PCs',
        ),
        migrations.DeleteModel(
            name='Servers',
        ),
        migrations.AddField(
            model_name='laptop',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salesite.Order'),
        ),
    ]
