# Generated by Django 2.1.2 on 2018-10-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesite', '0005_auto_20181011_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name='Thu Oct 11 14:34:56 2018'),
        ),
    ]
