# Generated by Django 2.1.2 on 2018-10-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesite', '0006_auto_20181011_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.CharField(default='user', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name='Tue Oct 23 14:31:26 2018'),
        ),
    ]
