# Generated by Django 2.1.2 on 2018-10-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesite', '0007_auto_20181023_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name='Tue Oct 23 14:32:34 2018'),
        ),
    ]
