# Generated by Django 2.1.2 on 2018-10-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesite', '0009_auto_20181023_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name='Wed Oct 24 16:22:55 2018'),
        ),
    ]
