# Generated by Django 2.1.2 on 2018-10-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesite', '0011_auto_20181030_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name='Tue Oct 30 13:54:21 2018'),
        ),
    ]
