# Generated by Django 2.1.2 on 2018-10-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesite', '0012_auto_20181030_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='order',
        ),
        migrations.RemoveField(
            model_name='pc',
            name='order',
        ),
        migrations.RemoveField(
            model_name='server',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='laptops',
            field=models.ManyToManyField(to='salesite.Laptop'),
        ),
        migrations.AddField(
            model_name='order',
            name='pcs',
            field=models.ManyToManyField(to='salesite.PC'),
        ),
        migrations.AddField(
            model_name='order',
            name='servers',
            field=models.ManyToManyField(to='salesite.Server'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
