# Generated by Django 2.1.2 on 2018-10-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesite', '0013_auto_20181030_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='pc',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='server',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
