# Generated by Django 2.1.2 on 2018-10-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesite', '0014_auto_20181030_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
