# Generated by Django 2.1.2 on 2018-10-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesite', '0015_auto_20181030_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
