# Generated by Django 2.1.2 on 2018-11-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesite', '0019_auto_20181101_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='role',
        ),
        migrations.AddField(
            model_name='customer',
            name='login',
            field=models.CharField(db_index=True, max_length=32, null=True),
        ),
    ]
