# Generated by Django 2.1.2 on 2018-11-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesite', '0020_auto_20181108_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='cost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pc',
            name='cost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='cost',
            field=models.FloatField(null=True),
        ),
    ]
