# Generated by Django 2.1.2 on 2018-11-12 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesite', '0021_auto_20181108_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='laptop',
            options={'verbose_name': 'Laptop', 'verbose_name_plural': 'Laptops'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='pc',
            options={'verbose_name': 'PC', 'verbose_name_plural': "PC's"},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'verbose_name': 'Server', 'verbose_name_plural': 'Servers'},
        ),
    ]
