# Generated by Django 2.1.2 on 2018-11-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesite', '0022_auto_20181112_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='cost',
            field=models.FloatField(null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='server',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='server',
            name='description',
            field=models.TextField(max_length=120, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='server',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='server',
            name='model_name',
            field=models.CharField(max_length=64, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='server',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity'),
        ),
    ]
